[build]
  # Build command for the frontend
  command = "npm run build"
  # Output directory for the built frontend
  publish = "dist"
  # Functions directory for serverless backend
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  # Don't fail on warnings
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirect all API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory where your TypeScript functions are
  node_bundler = "esbuild"
  # External modules that shouldn't be bundled
  external_node_modules = ["@supabase/supabase-js", "@google/generative-ai", "@anthropic-ai/sdk", "openai"]
  # Include server code
  included_files = ["server/**/*"]

# Specific function configuration for research compare endpoint
[[functions]]
  path = "/.netlify/functions/api"
  # Increase timeout for AI processing (requires Netlify Pro for >26 seconds)
  # Free tier max is 26 seconds, Pro tier allows up to 100 seconds
  timeout = 60
