[build]
  # Build command for the frontend
  command = "npm run build"
  # Output directory for the built frontend
  publish = "dist"
  # Functions directory for serverless backend
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  # Don't fail on warnings
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirect compare-research to dedicated function with longer timeout
[[redirects]]
  from = "/api/compare-research"
  to = "/.netlify/functions/compare-research/api/compare-research"
  status = 200

# Redirect all other API requests to main serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory where your TypeScript functions are
  node_bundler = "esbuild"
  # External modules that shouldn't be bundled
  external_node_modules = ["@supabase/supabase-js", "@google/generative-ai", "@anthropic-ai/sdk", "openai"]
  # Include server code
  included_files = ["server/**/*"]

# Individual function configuration
[functions."api"]
  # Maximum timeout - 26 seconds on free tier
  timeout = 26

# Separate function for long-running research comparison
[functions."compare-research"]
  # Set to maximum - Netlify limits: Free tier = 26s, Pro tier = 100s
  # Background functions can run longer but need different invocation pattern
  timeout = 300
