services:
  - type: web
    name: synapse-api
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: AI_PROVIDER
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
    healthCheckPath: /health
